service: suntimes-service

provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-2

plugins:
  - serverless-python-requirements

package:
 exclude:
   - bin
   - include
   - lib
   - local
   - node_modules

functions:
  sunrise:
    handler: handler.sunrise
    events:
      - http:
          path: sunrise/bute
          method: get
  sunset:
    handler: handler.sunset
    events:
      - http:
          path: sunset/bute
          method: get
